version: "3"
services:
  xxljob:
    hostname: xxl-job-admin
    container_name: xxl-job-admin
    restart: always
    build: ./xxl/       #需要构建的Dockerfile文件
    ports:
      - "38000:8080"      #容器端口映射到宿主机的端口
    networks:
      - push-center

  pushcenter:
    hostname: yuoumall-push-center
    container_name: yuoumall-push-center
    restart: always
    build: ./web/       #需要构建的Dockerfile文件
    ports:
      - "38001:8081"      #容器端口映射到宿主机的端口
    environment:
      PARAMS: '--xxl.job.admin.addresses=http://192.168.76.138:38000/xxl-job-admin'
    networks:
      - push-center
    depends_on:
      - xxljob

networks:
  push-center:
    driver: bridge
#    environment:
#      username: lzz    #springboot项目中连接数据库需要的环境变量
#      password: lzz      # mysql:3306 这里不能写localhost:3306，应该写下面这种，mysql对应的是服务名称
#      url: jdbc:mysql://mysql:3306/library?useUnicode=true&characterEncoding=utf8
#    depends_on:      #web服务依赖mysql服务，要等mysql服务先启动
#      - mysql
#version: '3'
#services:
#  proxy:
#    image: nginx:1.16.1
#    ports:
#      - 80:80
#      - 443:443
#    privileged: true
#    restart: always
#    networks:
#      webapp:
#        ipv4_address: 172.16.238.10
#    volumes:
#      - /opt/acme/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - /opt/acme/nginx/conf/keys:/etc/nginx/keys
#      - /opt/acme/nginx/conf/conf.d:/etc/nginx/conf.d
#      - /opt/acme/nginx/www:/usr/share/nginx/html
#      - /opt/acme/nginx/logs:/var/log/nginx
#  cache:
#    image: redis:5.0
#    privileged: true
#    restart: always
#    networks:
#      webapp:
#        ipv4_address: 172.16.238.12
#    ports:
#      - 6379:6379
#    volumes:
#      - /opt/acme/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
#      - /opt/acme/redis/data:/data
#  cms:
#    build: .
#    restart: always
#    networks:
#      webapp:
#        ipv4_address: 172.16.238.13
#    ports:
#      - 8888:8888
#      - 8889:8889
#      - 8000:8000 #use for debug
#networks:
#  webapp:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.16.238.0/24
#          gateway: 172.16.238.1